name: Deploy Diplomas API to Cloudflare Workers

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: finki-hub/.github/.github/workflows/cloudflare-workers.yaml@main
    with:
      working-directory: diplomas-api
      install-directory: .
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
