name: Lint Masters API

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tsc:
    uses: finki-hub/.github/.github/workflows/tsc.yaml@main
    with:
      script: check:masters-api
  eslint:
    uses: finki-hub/.github/.github/workflows/eslint.yaml@main
    with:
      script: lint:masters-api
